version: '3.8'

services:
  vreetvos-app:
    # The image will be pulled from GHCR.
    # IMPORTANT: Replace YOUR_GITHUB_USERNAME and YOUR_REPO_NAME with your actual GitHub username/organization and repository name.
    image: ghcr.io/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME:latest
    container_name: vreetvos-app-container
    ports:
      - "8080:8080"
    volumes:
      - vreetvos_db_data:/data
    # Environment variables are set in the Dockerfile.
    # Restart policy can be useful for production-like behavior
    restart: unless-stopped

volumes:
  vreetvos_db_data:
    # driver: local
