name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Note on Registry Choice:
    # This workflow is configured for GitHub Container Registry (GHCR).
    # To use a different registry (e.g., Docker Hub):
    # 1. Change the 'registry' input below if necessary (for Docker Hub, it can often be omitted).
    # 2. Update 'username' to your registry username (e.g., ${{ secrets.DOCKERHUB_USERNAME }}).
    # 3. Update 'password' to use your registry token/password (e.g., ${{ secrets.DOCKERHUB_TOKEN }}).
    # 4. Create these secrets (e.g., DOCKERHUB_USERNAME, DOCKERHUB_TOKEN) in your
    #    GitHub repository settings under "Secrets and variables" > "Actions".
    # 5. Update the image name in the 'Extract metadata' step below.
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        # Image name for GHCR.
        # For Docker Hub, you'd use something like: YOUR_DOCKERHUB_USERNAME/${{ github.event.repository.name }}
        # Ensure this matches the registry you're logging into.
        images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
        tags: |
          type=sha,format=long,prefix=
          latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        # cache-from: type=gha  # Removed
        # cache-to: type=gha,mode=max # Removed
